version: 2

models:
  - name: player_stats_gold
    description: "Statistiques des joueurs NBA transformées pour la couche gold"
    schema: scouting_dbt_gold

    columns:
      - name: player
        description: "Nom du joueur"
        tests:
          - not_null
      - name: player_id
        description: "Identifiant unique du joueur"
        tests:
          - not_null
      - name: season
        description: "Saison NBA"
        tests:
          - not_null
      - name: games_played
        description: "Nombre de matchs joués"
        tests:
          - not_null
      - name: points_per_game
        description: "Points par match"
        tests:
          - not_null