version: 2

models:

  - name: gold_top_scorers
    description: "Top marqueurs par saison avec efficacité et productivité"
    columns:
      - name: player
        description: "Nom du joueur"
      - name: season
        description: "Saison NBA"
      - name: team
        description: "Équipe principale"
      - name: total_points
        description: "Total des points marqués"
      - name: total_minutes
        description: "Total des minutes jouées"
      - name: pts_per_min
        description: "Points marqués par minute"
      - name: avg_fg_percent
        description: "Précision moyenne au tir (field goal %)"
